#!/bin/bash

# Simple shell script for deploying code to the plugins directory used by 
# docker to inject code without needing to use PIP.  Only during dev/test.


# Pull latest source, unless told not to with --nopull or -n
if [ "$1" != "-nopull" ] && [ "$1" != "-n" ]; then
    # Enable command tracing
    set -x
    # Make sure we have the latest code
    git pull
fi

# Disable command tracing
set +x

# Definviews e the target directory
target_dir=~/inventree-data/plugins/inventree-part-templates/

# Enable command tracing
set -x

# Ensure the target directory exists and is empty
rm -rf "${target_dir}"
mkdir -p "${target_dir}"

# Copy the new files into the target directory
cp -r . "${target_dir}"
# Remove this deploy script, as it is only valid from the git repo
rm "${target_dir}deploy"

# Restart the InvenTree server container
docker container restart inventree-server

# Wait for the server to be fully up
sleep 14

